language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    # if OPS conda is working, use the following 3 lines
    #- conda build devtools/conda-recipe
    #- source activate _test
    #- conda clean -pltis --yes
    # if OPS conda is failing, use the following 2 lines
    - source devtools/no-ops-conda/make_build.sh
    - source devtools/no-ops-conda/build.sh
    - python -c "import openpathsampling; print 'OPS version' + openpathsampling.version.full_version"
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
