language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    - conda config --set always_yes true
    #- source devtools/conda-ops-recipe/other_conda_build.sh
    - source devtools/conda-ops-recipe/get_ops_reqs.sh
    #- conda install --file devtools/conda-ops-recipe/ops_reqs.txt
    - conda build devtools/conda-ops-recipe  # if OPS conda is failing
    #- conda build devtools/conda-recipe
    
    - source activate _test
    - conda clean -pltis --yes
    - python -c "import openpathsampling; print 'OPS version' + openpathsampling.version.full_version"
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
