language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - conda clean -pltis --yes
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    - conda build devtools/conda-recipe
    
    - source activate _test
    - python -c "import openpathsampling; print 'OPS version' + openpathsampling.version.full_version"
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
