language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    - nosetests -v

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
